// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WdCn19E8sJjtnLXu8i8UnvpffQKkPpo',
    appId: '1:13564294004:android:9919ac8251e1e278c0f221',
    messagingSenderId: '13564294004',
    projectId: 'partiu-479902',
    storageBucket: 'partiu-479902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9DcPOLt4FggQqmHPJd7JRlWdhR0XV4gQ',
    appId: '1:13564294004:ios:0658c8691dc9dbbac0f221',
    messagingSenderId: '13564294004',
    projectId: 'partiu-479902',
    storageBucket: 'partiu-479902.firebasestorage.app',
    androidClientId: '13564294004-289p5qit2gsntuu73uk9b92s86damooi.apps.googleusercontent.com',
    iosClientId: '13564294004-3edvbujvrqv197n6ttpbus2gibprqsr6.apps.googleusercontent.com',
    iosBundleId: 'com.maikelgalvao.partiu',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndVUhkmts_WbngOH99Z2_OX-Y4pvfySc',
    appId: '1:13564294004:web:a7188e42eb345ccdc0f221',
    messagingSenderId: '13564294004',
    projectId: 'partiu-479902',
    authDomain: 'partiu-479902.firebaseapp.com',
    storageBucket: 'partiu-479902.firebasestorage.app',
  );

}